server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # SPA routing  
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Кэш 
  location ~* \.(js|css|png|jpg|svg|ico)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}